version: "3.8"
services:
    nats:
        container_name: nats
        command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
        # entrypoint: "/nats-server -c nats-server.conf -DV"
        image: nats
        ports:
            - "4222:4222"
            - "6222:6222"
            - "8222:8222"
        networks: ["nats"]
    gateway:
        build:
            context: .
            dockerfile: ./gateway/Dockerfile
        container_name: gateway
        command: npm run start:dev
        ports:
            - 3001:3001
        volumes:
            - ./gateway:/app
            - ./app/node_modules

    user:
        # volumes:
        #     - ./user:/app
        build:
            context: .
            dockerfile: ./user/Dockerfile
        container_name: user
        command: npm run start:dev
        networks: ["nats"]
        depends_on: ["nats"]
        volumes:
            - ./user:/app
            - ./app/node_modules
networks:
    nats:
